In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
labels = pd.read_csv('labeled_anomalies.csv')

In [3]:
labels.head()

,chan_id,spacecraft,anomaly_sequences,class,num_values
0,P-1,SMAP,"[[2149, 2349], [4536, 4844], [3539, 3779]]","[contextual, contextual, contextual]",8505
1,S-1,SMAP,"[[5300, 5747]]",[point],7331
2,E-1,SMAP,"[[5000, 5030], [5610, 6086]]","[contextual, contextual]",8516
3,E-2,SMAP,"[[5598, 6995]]",[point],8532
4,E-3,SMAP,"[[5094, 8306]]",[point],8307

In [4]:
labels.info()

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   chan_id            82 non-null     str
 1   spacecraft         82 non-null     str
 2   anomaly_sequences  82 non-null     str
 3   class              82 non-null     str
 4   num_values         82 non-null     int64
dtypes: int64(1), str(4)
memory usage: 3.3 KB

In [5]:
A1 = np.load("data/data/train/A-1.npy")
print(A1)

[[0.999 0.    0.    ... 0.    0.    0.   ]
 [0.999 0.    0.    ... 0.    0.    0.   ]
 [0.999 0.    0.    ... 0.    0.    0.   ]
 ...
 [0.999 0.    0.    ... 0.    0.    0.   ]
 [0.999 0.    0.    ... 0.    0.    0.   ]
 [0.999 0.    0.    ... 0.    0.    0.   ]]

In [6]:
df_anomalies = pd.read_csv("labeled_anomalies.csv")

In [7]:
# Display unique telemetry channels
print(df_anomalies['chan_id'].unique())

# Check anomalies for a specific channel
df_anomalies[df_anomalies['chan_id'] == 'P-1']

<StringArray>
[ 'P-1',  'S-1',  'E-1',  'E-2',  'E-3',  'E-4',  'E-5',  'E-6',  'E-7',
  'E-8',  'E-9', 'E-10', 'E-11', 'E-12', 'E-13',  'A-1',  'D-1',  'P-2',
  'P-3',  'D-2',  'D-3',  'D-4',  'A-2',  'A-3',  'A-4',  'G-1',  'G-2',
  'D-5',  'D-6',  'D-7',  'F-1',  'P-4',  'G-3',  'T-1',  'T-2',  'D-8',
  'D-9',  'F-2',  'G-4',  'T-3', 'D-11', 'D-12',  'B-1',  'G-6',  'G-7',
  'P-7',  'R-1',  'A-5',  'A-6',  'A-7', 'D-13',  'A-8',  'A-9',  'F-3',
  'M-6',  'M-1',  'M-2',  'S-2', 'P-10',  'T-4',  'T-5',  'F-7',  'M-3',
  'M-4',  'M-5', 'P-15',  'C-1',  'C-2', 'T-12', 'T-13',  'F-4',  'F-5',
 'D-14',  'T-9', 'P-14',  'T-8', 'P-11', 'D-15', 'D-16',  'M-7',  'F-8']
Length: 81, dtype: str

,chan_id,spacecraft,anomaly_sequences,class,num_values
0,P-1,SMAP,"[[2149, 2349], [4536, 4844], [3539, 3779]]","[contextual, contextual, contextual]",8505